/**
 * Demo mode payloads.
 *
 * BUILD_SPEC phase 7: `?demo=true` serves cached JSON for the five locked demo
 * items and makes no network call. "Venue WiFi has ended more hackathon runs
 * than bad code."
 *
 * The payloads are generated by `npm run demo:build` and imported statically,
 * so they are inside the Worker bundle — there is nothing to fetch even in
 * principle.
 */
import demoPayloads from "../../../data/demo/payloads.json" with { type: "json" };
import demoBarcodes from "../../../data/demo/barcodes.json" with { type: "json" };
import type { CalculationResult } from "../../../engine/types.ts";
import type { BarcodeResult } from "../../../resolvers/barcode.ts";

const CACHE = demoPayloads as unknown as Record<string, CalculationResult>;

/**
 * Real Open Food Facts responses, snapshotted at build time.
 *
 * `/api/calculate` never needed demo mode — the engine reads a local bundle and
 * makes no network call at all. The route that *does* is `/api/resolve`, which
 * calls Open Food Facts for a barcode and Gemini for a photo. This is the half
 * that venue WiFi can take down mid-demo.
 */
const BARCODES = demoBarcodes as unknown as Record<string, BarcodeResult>;

export { DEMO_ITEMS } from "./demo-items.ts";

export function loadDemo(productId: string): CalculationResult | null {
  return CACHE[productId] ?? null;
}

export function loadDemoBarcode(ean: string): BarcodeResult | null {
  return BARCODES[ean.replace(/\D/g, "")] ?? null;
}

export function demoIndex(): string[] {
  return Object.keys(CACHE);
}

export function demoBarcodeIndex(): string[] {
  return Object.keys(BARCODES);
}
